extends: relaxed
rules:
  line-length:
    max: 180
    level: warning
  indentation:
    indent-sequences: consistent
  comments-indentation: disable
  new-line-at-end-of-file:
    level: info
  trailing-spaces:
    level: info
ignore: |
  **/kms_key_with_full_permissions/test/positive.yaml
