name: kics-github-action

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@252e73959bd4809a14863cbfbb42d7a90d5a4860 # v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "./Dockerfile"
          ignore_on_exit: results
          enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results
