name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
  grype:
    name: Grype Scan
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        kics-docker: [ "Dockerfile"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          load: true
          context: ./
          file: ./${{ matrix.kics-docker }}
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: kics:sec-tests-${{ github.sha }}
          build-args: |
            VERSION=development
            COMMIT=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: kics:sec-tests-${{ github.sha }}
          fail-build: true
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
